"""Add new column to TelegramUser

Revision ID: 802070bfad2e
Revises: b8507ec0f413
Create Date: 2024-07-25 15:56:09.158588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802070bfad2e'
down_revision: Union[str, None] = 'b8507ec0f413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
